# Generated by Django 5.1.4 on 2024-12-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
