# Generated by Django 5.1.4 on 2024-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
